### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-sinatra-assets-and-layouts#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](https://vast-savannah-6310.herokuapp.com/) and meets the following [project](http://lansingcodelab.com/lessons/sinatra-assets-and-layouts/1) criteria:
- [x] The code from the previous Sinatra project is copied into this project folder
- [x] You have more than one view file served to more than one route
- [x] A `.css` and `.js` file are included on every page via a `link` and `script` element, respectively (make sure those files have some effect on the page so that we know it worked)
- [x] A `layout.erb` file is used to DRY up your HTML
- [x] There are not _any_ duplicate lines of code between view files

So, there are duplicate lines of code because I'm using bootstrap and I have divs with classes. I can see how I would maybe create different fields in my layout.erb and then add content for those fields in my views. But that seems out of scope for this lesson.

**Comment by chrisvfritz** [comment]
So it looks like you have a lot of your assets inside your public folder, but some of them are outside of it, like the `js` and `fonts` folder. It looks like you just forgot to delete the `js` folder, as it has nothing else you'd need in the project. For the fonts, folder, I'd recommend moving that into the `public` folder though, if you want Bootstrap to be able to access them.

**Comment by KatieMFritz** [comment]
should be fixed now!

**Comment by chrisvfritz** [comment]
:shipit: Marvelous!
